### ISSUE TITLE
[Feature Request] 自动更新版本

### ISSUE THREAD

**Issue by kands-code** [flathub/io.github.Icalingua.Icalingua#43]
正如 #13 所说，现在 flathub bot 在每次 Icalingua++ 更新后都有一个 pr 来测试更新版本

如果可以自动合并这些 pr 应该是合适的

现在最新版本已经到了 2.9.2 了，但是 Flathub 版本还是 2.8.5

**Comment by Clansty** [comment]
Merged #29
